import Foundation

// App-language strings (English / हिन्दी) for the chrome the viewer reads most:
// tab titles, Settings labels, the paywall's primary copy and the help
// assistant. A code table rather than .strings files: generate_xcodeproj.rb
// bundles only the asset catalog, the privacy manifest and the fonts, so a
// Localizable.strings would never reach the app bundle. Content languages
// (hi/ta/te) are a separate, multi-select choice — this is the UI language.
//
// Usage: `model.t("tab.home")` (AppModel reads its `uiLanguage`). Keys missing a
// Hindi line fall back to English so a half-translated key never renders empty.

enum L10n {
    static let supported: [(code: String, native: String, name: String)] = [
        ("en", "English", "English"),
        ("hi", "हिन्दी", "Hindi"),
    ]

    static func string(_ key: String, lang: String) -> String {
        if lang == "hi", let s = hi[key] { return s }
        return en[key] ?? key
    }

    private static let en: [String: String] = [
        // Tabs
        "tab.home": "Home",
        "tab.browse": "Browse",
        "tab.mylist": "My list",
        "tab.profile": "Profile",
        // Settings
        "settings.title": "Settings",
        "settings.language": "Language",
        "settings.contentLanguage": "Content language",
        "settings.appLanguage": "App language",
        "settings.appLanguage.footer": "The language of menus and buttons. Stories keep their own languages.",
        "settings.playback": "Playback",
        "settings.dataSaver": "Data saver",
        "settings.autoUnlock": "Auto-unlock next episodes",
        "settings.previews": "Autoplay trailers",
        "settings.previews.caption": "Muted previews on Home",
        "settings.playback.footer": "Data saver caps streaming quality on mobile data. Auto-unlock charges coins only when an episode starts.",
        "settings.notifications": "Notifications",
        "settings.alerts": "New episode alerts",
        "settings.alerts.footer": "One alert when your next episode drops. Never between 11 pm and 8 am, at most two a day.",
        "settings.parental": "Parental lock",
        "settings.parental.set": "Set parental lock",
        "settings.parental.change": "Change parental lock",
        "settings.parental.remove": "Remove parental lock",
        "settings.parental.footer": "A PIN is asked before playing U/A 16+ and A-rated titles (IT Rules 2021). Changing or removing the lock asks for the current PIN.",
        "settings.account": "Account",
        "settings.signOutDevices": "Sign out of other devices",
        "settings.signOutDevices.done": "Other devices were signed out",
        "settings.about": "About",
        "settings.help": "Help & grievance",
        "settings.legal": "Terms · Privacy Notice",
        "settings.delete": "Delete account",
        // Paywall + packs
        "paywall.unlock": "Unlock episode",
        "paywall.unlocking": "Unlocking…",
        "paywall.getCoins": "Get coins",
        "paywall.buyOnce": "Buy once, keep watching",
        "packs.title": "Coin packs",
        "packs.footer": "Payment is handled by Apple. Coins never expire while your account exists. Prices include GST.",
        "packs.restore": "Restore purchases",
        "packs.restored": "Purchases restored",
        "packs.terms": "Terms",
        "packs.confirming": "Confirming with the App Store. Your episode unlocks automatically.",
        "packs.stillConfirming": "Still confirming — you can keep browsing.",
        "packs.pending.banner": "This purchase needs approval from your family organizer. We'll unlock the episode the moment it's approved.",
        "packs.pending.notCharged": "You haven't been charged yet.",
        "packs.failed": "Payment didn't go through. You weren't charged.",
        "packs.retry": "Retry",
        "packs.done": "Done",
        "packs.credited": "coins added",
        // Continue watching
        "continue.title": "Continue watching",
        "continue.seeAll": "See all",
        "continue.empty.title": "Nothing in progress",
        "continue.empty.body": "Start any episode and it shows up here, right where you left it.",
        // Help assistant
        "assistant.title": "Chat with us",
        "assistant.card": "Answers in Hindi and English. A person steps in when needed.",
        "assistant.greeting": "Hi! Ask me about coins, free episodes, refunds, the parental lock, languages or playback — in English or Hindi.",
        "assistant.placeholder": "Ask a question",
        "assistant.person": "Talk to a person",
        "assistant.fallback": "I don't have an answer for that yet. Tap \"Talk to a person\" and the grievance officer picks it up — acknowledged within 24 hours.",
        "assistant.footer": "Answers come from Katha's built-in help — no AI service is contacted.",
        "assistant.send": "Send",
        // Reminders
        "reminder.on": "Reminder on",
        "reminder.off": "Remind me",
        "reminder.toast.on": "We'll nudge you when a new episode drops",
        "reminder.toast.off": "Reminder turned off",
        // Player
        "player.tracks": "Audio & subtitles",
        "player.audio": "Audio",
        "player.subtitles": "Subtitles",
        "player.subtitles.off": "Off",
        "player.subtitles.none": "No subtitles for this episode yet.",
        // Parental lock recovery
        "pin.forgot": "Forgot PIN?",
        "pin.reset.title": "Reset the parental lock",
        "pin.reset.body": "We'll send a code to the phone on this account. Entering it removes the lock; set a new PIN afterwards in Settings.",
        "pin.reset.send": "Send code",
        "pin.reset.enter": "Enter the code",
        "pin.reset.guest": "Resetting the PIN needs a phone sign-in. Sign in with your number from Profile, then come back here.",
        "pin.reset.done": "Parental lock removed",
        "action.cancel": "Cancel",
        "action.notNow": "Not now",
        "otp.placeholder": "4-digit code",
        "login.phone.placeholder": "10-digit mobile number",
        "delete.title": "Delete your account?",
        "delete.coins": "Your coins and unlocked episodes are removed.",
        "delete.data": "Your phone number and watch history are deleted within 30 days.",
        "delete.apple": "Purchases made through Apple follow Apple's refund policy.",
        "delete.understood": "I understand my coins won't be refunded.",
        "delete.confirm": "Delete account",
        "delete.deleting": "Deleting…",
        "delete.keep": "Keep my account",
        // Home (2.1)
        "home.checkin.title": "Daily check-in",
        "home.checkin.body": "Claim today's %d coins",
        "home.checkin.body.plain": "Claim today's coins",
        "home.checkin.claim": "Claim",
        "home.checkin.toast": "+%d coins · day streak",
        "home.search": "Search",
        "home.contentLanguage": "Content language",
        "home.episodes": "%d episodes",
        "home.firstFree": "First %d free",
        "home.playE1": "Play E1",
        "home.featured": "%@, featured story",
        "home.offline.title": "Can't reach Katha",
        "home.offline.body": "Check your connection and try again.",
        "home.offline.retry": "Retry",
        "home.offline.retrying": "Retrying…",
        "home.loading": "Loading stories",
        // Browse (2.2)
        "browse.title": "Browse",
        "browse.all": "All",
        "browse.everything": "Everything",
        "browse.empty.title": "Nothing here yet",
        "browse.empty.body": "Try another genre — or switch language.",
        // Search (2.3)
        "search.title": "Search",
        "search.placeholder": "Series, people, tropes",
        "search.clear": "Clear search",
        "search.recent": "Recent",
        "search.trending": "Trending",
        "search.series": "Series",
        "search.people": "People",
        "search.eps": "%d eps",
        "search.empty.title": "No results for “%@”",
        "search.empty.body": "Check the spelling — or try a genre like Romance or Thriller.",
        "person.cast": "Cast",
        "person.series": "%d series",
        // Series (2.4)
        "series.pricing": "Free · %1$d episodes, then %2$d coins%3$@ each",
        "series.play1": "Play episode 1",
        "series.continue": "Continue E%d",
        "series.save": "Save to My list",
        "series.unsave": "Remove from My list",
        "series.reminderHint": "New-episode reminder for this series",
        "series.episode": "Episode %d",
        "series.episode.free": ", free",
        "series.episode.locked": ", locked",
        "series.episode.here": ", continue here",
        // My list (4.4)
        "mylist.empty.title": "Nothing saved yet",
        "mylist.empty.body": "Tap the bookmark on any series and it lands here.",
        "mylist.remove": "Remove from My list",
        // Continue watching (4.5)
        "continue.left.minutes": "%d min left",
        "continue.left.under": "<1 min left",
        "continue.resume": "Resume",
        "continue.resumeHint": "Resumes the episode",
        // Wallet (3.5)
        "wallet.title": "Wallet",
        "wallet.balance": "Balance",
        "wallet.getCoins": "Get coins",
        "wallet.allPacks": "All packs",
        "wallet.split": "%1$d bought · %2$d bonus — bonus is spent first. Coins never expire.",
        "wallet.footer": "Payment is handled by Apple. Prices include GST. Coins never expire while your account exists.",
        "wallet.history": "History",
        "wallet.history.empty": "No transactions yet — coins you buy and spend show up here.",
        "wallet.today": "Today",
        "wallet.yesterday": "Yesterday",
        "wallet.row.purchase": "Coin pack",
        "wallet.row.bonus": "Bonus coins",
        "wallet.row.checkin": "Daily check-in",
        "wallet.row.referral": "Referral reward",
        "wallet.row.bundle": "Series bundle unlock",
        "wallet.row.unlock": "Episode unlock",
        "wallet.row.refund": "Refund",
        "wallet.row.adjust": "Support adjustment",
        "wallet.src.web": "Web store",
        "wallet.src.appstore": "App Store",
        // Profile (4.1)
        "profile.title": "Profile",
        "profile.invoices": "Invoices",
        "profile.replayTips": "Replay tips",
        "profile.signOut": "Sign out",
        "profile.signIn": "Sign in",
        "profile.member": "Katha member",
        "profile.signedIn": "Signed in",
        "profile.guest.title": "You're browsing as a guest",
        "profile.guest.body": "Create an account to keep your coins and progress.",
        "profile.coins": "%d coins",
        "profile.version": "Version %@",
        // Invoices (4.8)
        "invoices.empty.title": "No invoices yet",
        "invoices.empty.body": "Coins bought on the Katha website (UPI) are invoiced here. App Store purchases are invoiced by Apple.",
        // Help (4.6)
        "help.common": "Common questions",
        "help.contact": "Contact",
        "help.contact.footer": "Complaints are acknowledged within 24 hours and resolved within 15 days, as required under the IT Rules, 2021. Support hours 9 am–9 pm IST.",
        "help.faq.coins.q": "How do coins work?",
        "help.faq.coins.a": "The first %1$d episodes of every series are free. After that, each episode costs %2$d coins%3$@. Buy packs once — coins never expire.",
        "help.faq.coins.a.plain": "The first episodes of every series are free; after that each one costs coins. Buy packs once — coins never expire.",
        "help.faq.missing.q": "I paid but didn't get my coins",
        "help.faq.missing.a": "Pull to refresh your Wallet, then tap Restore purchases. If the coins still haven't landed within a few minutes, contact support — verified failed transactions are re-credited.",
        "help.faq.refunds.q": "Refunds and cancellations",
        "help.faq.refunds.a": "App Store purchases are refunded by Apple under Apple's policy (reportaproblem.apple.com). Coins bought on the web are refundable within 7 days if unspent.",
        "help.faq.parental.q": "Parental controls",
        "help.faq.parental.a": "Set a PIN in Settings → Parental lock. U/A 16+ and A-rated titles then require it before playing.",
        "help.grievance.header": "File a grievance",
        "help.grievance.footer": "Goes straight to the grievance officer, no email needed.",
        "help.grievance.contact": "Your email or phone",
        "help.grievance.subject": "What went wrong?",
        "help.grievance.file": "File grievance",
        "help.grievance.filing": "Filing…",
        "help.grievance.ack": "Filed as %@. We'll acknowledge within 24 hours and resolve within 15 days.",
        "help.grievance.error": "Couldn't file right now — email us below instead.",
        // Player (3.1 / 3.2 / 3.4)
        "player.like": "Like",
        "player.liked": "Liked",
        "player.share": "Share",
        "player.timeLeft": "%@ left",
        "player.locked": "Episode %d is locked",
        "player.unlockFor": "Unlock for %d coins",
        "player.unlockForRupees": "Unlock for %1$d coins  ·  ≈ ₹%2$@",
        "player.offline.title": "Connection lost",
        "player.offline.retry": "Retry",
        "player.upNext": "Up next: E%d",
        "player.playNext": "Play next episode",
        "player.finished": "You finished %@",
        "player.finished.body": "New stories drop every week.",
        "player.backHome": "Back to Home",
        "player.recording.title": "Recording isn't supported",
        "player.recording.body": "Playback resumes when screen recording stops.",
        "player.screenshot": "Screenshots of episodes aren't allowed",
        "player.autoUnlocked": "−%1$d coins · E%2$d unlocked",
        "player.rate2x": "Playing at 2 times speed",
        "player.subtitles.footer": "Subtitles follow your system caption style. A language the stream doesn't carry yet is remembered and applied when it does.",
        "player.track.remembered": "Remembered",
        "player.track.notHere": "Not in this episode",
        "drawer.title": "Episodes",
        "drawer.count": "%1$d · 1–%2$d free",
        "drawer.autoUnlock.caption": "Charges %d coins only when an episode starts",
        "drawer.autoUnlock.caption.short": "Charges only when an episode starts",
    ]

    private static let hi: [String: String] = [
        "tab.home": "होम",
        "tab.browse": "ब्राउज़",
        "tab.mylist": "मेरी सूची",
        "tab.profile": "प्रोफ़ाइल",
        "settings.title": "सेटिंग्स",
        "settings.language": "भाषा",
        "settings.contentLanguage": "कहानियों की भाषा",
        "settings.appLanguage": "ऐप की भाषा",
        "settings.appLanguage.footer": "मेनू और बटनों की भाषा। कहानियाँ अपनी भाषा में ही रहती हैं।",
        "settings.playback": "प्लेबैक",
        "settings.dataSaver": "डेटा सेवर",
        "settings.autoUnlock": "अगले एपिसोड अपने आप अनलॉक करें",
        "settings.previews": "ट्रेलर अपने आप चलाएँ",
        "settings.previews.caption": "होम पर बिना आवाज़ के प्रीव्यू",
        "settings.playback.footer": "डेटा सेवर मोबाइल डेटा पर क्वालिटी सीमित रखता है। ऑटो-अनलॉक सिर्फ़ एपिसोड शुरू होने पर सिक्के लेता है।",
        "settings.notifications": "सूचनाएँ",
        "settings.alerts": "नए एपिसोड की सूचना",
        "settings.alerts.footer": "अगला एपिसोड आते ही एक सूचना। रात 11 से सुबह 8 के बीच कभी नहीं, दिन में ज़्यादा से ज़्यादा दो।",
        "settings.parental": "पैरेंटल लॉक",
        "settings.parental.set": "पैरेंटल लॉक लगाएँ",
        "settings.parental.change": "पैरेंटल लॉक बदलें",
        "settings.parental.remove": "पैरेंटल लॉक हटाएँ",
        "settings.parental.footer": "U/A 16+ और A रेटेड कहानियाँ चलाने से पहले PIN पूछा जाता है (IT नियम 2021)। लॉक बदलने या हटाने के लिए मौजूदा PIN चाहिए।",
        "settings.account": "खाता",
        "settings.signOutDevices": "बाकी डिवाइस से साइन आउट करें",
        "settings.signOutDevices.done": "बाकी डिवाइस साइन आउट हो गए",
        "settings.about": "जानकारी",
        "settings.help": "मदद और शिकायत",
        "settings.legal": "शर्तें · गोपनीयता सूचना",
        "settings.delete": "खाता हटाएँ",
        "paywall.unlock": "एपिसोड अनलॉक करें",
        "paywall.unlocking": "अनलॉक हो रहा है…",
        "paywall.getCoins": "सिक्के लें",
        "paywall.buyOnce": "एक बार खरीदें, देखते रहें",
        "packs.title": "सिक्कों के पैक",
        "packs.footer": "भुगतान Apple संभालता है। खाता रहते सिक्के कभी खत्म नहीं होते। दामों में GST शामिल है।",
        "packs.restore": "खरीदारी वापस लाएँ",
        "packs.restored": "खरीदारी वापस आ गई",
        "packs.terms": "शर्तें",
        "packs.confirming": "App Store से पुष्टि हो रही है। आपका एपिसोड अपने आप अनलॉक हो जाएगा।",
        "packs.stillConfirming": "पुष्टि अभी बाकी है — आप देखते रह सकते हैं।",
        "packs.pending.banner": "इस खरीद के लिए आपके फ़ैमिली ऑर्गनाइज़र की मंज़ूरी चाहिए। मंज़ूरी मिलते ही एपिसोड अनलॉक हो जाएगा।",
        "packs.pending.notCharged": "अभी आपसे कोई पैसा नहीं लिया गया है।",
        "packs.failed": "भुगतान नहीं हो पाया। आपसे पैसा नहीं लिया गया।",
        "packs.retry": "फिर कोशिश करें",
        "packs.done": "ठीक है",
        "packs.credited": "सिक्के जुड़ गए",
        "continue.title": "देखना जारी रखें",
        "continue.seeAll": "सभी देखें",
        "continue.empty.title": "अभी कुछ चल नहीं रहा",
        "continue.empty.body": "कोई भी एपिसोड शुरू करें — वह यहाँ वहीं से मिलेगा जहाँ आपने छोड़ा था।",
        "assistant.title": "हमसे बात करें",
        "assistant.card": "हिन्दी और अंग्रेज़ी में जवाब। ज़रूरत पड़ने पर एक इंसान जुड़ता है।",
        "assistant.greeting": "नमस्ते! सिक्के, मुफ़्त एपिसोड, रिफ़ंड, पैरेंटल लॉक, भाषा या प्लेबैक के बारे में पूछिए — हिन्दी या अंग्रेज़ी में।",
        "assistant.placeholder": "सवाल पूछें",
        "assistant.person": "किसी इंसान से बात करें",
        "assistant.fallback": "इसका जवाब अभी मेरे पास नहीं है। \"किसी इंसान से बात करें\" दबाएँ — शिकायत अधिकारी 24 घंटे में जवाब देते हैं।",
        "assistant.footer": "जवाब Katha की अपनी मदद-सूची से आते हैं — किसी AI सेवा से संपर्क नहीं होता।",
        "assistant.send": "भेजें",
        "reminder.on": "याद दिलाना चालू",
        "reminder.off": "याद दिलाएँ",
        "reminder.toast.on": "नया एपिसोड आते ही हम बताएँगे",
        "reminder.toast.off": "याद दिलाना बंद",
        "player.tracks": "ऑडियो और सबटाइटल",
        "player.audio": "ऑडियो",
        "player.subtitles": "सबटाइटल",
        "player.subtitles.off": "बंद",
        "player.subtitles.none": "इस एपिसोड के सबटाइटल अभी नहीं हैं।",
        "pin.forgot": "PIN भूल गए?",
        "pin.reset.title": "पैरेंटल लॉक रीसेट करें",
        "pin.reset.body": "इस खाते के फ़ोन पर कोड भेजा जाएगा। कोड डालते ही लॉक हट जाएगा; बाद में सेटिंग्स में नया PIN लगाएँ।",
        "pin.reset.send": "कोड भेजें",
        "pin.reset.enter": "कोड डालें",
        "pin.reset.guest": "PIN रीसेट के लिए फ़ोन से साइन इन ज़रूरी है। प्रोफ़ाइल से अपने नंबर से साइन इन करें, फिर यहाँ लौटें।",
        "pin.reset.done": "पैरेंटल लॉक हट गया",
        "action.cancel": "रद्द करें",
        "action.notNow": "अभी नहीं",
        "otp.placeholder": "4 अंकों का कोड",
        "login.phone.placeholder": "10 अंकों का मोबाइल नंबर",
        "delete.title": "खाता हटाना है?",
        "delete.coins": "आपके सिक्के और अनलॉक किए एपिसोड हट जाएँगे।",
        "delete.data": "आपका फ़ोन नंबर और देखने का इतिहास 30 दिन में मिटा दिया जाएगा।",
        "delete.apple": "Apple से की गई खरीद पर Apple की रिफ़ंड नीति लागू होती है।",
        "delete.understood": "मैं समझता/समझती हूँ कि सिक्के वापस नहीं मिलेंगे।",
        "delete.confirm": "खाता हटाएँ",
        "delete.deleting": "हटाया जा रहा है…",
        "delete.keep": "खाता रहने दें",
        // होम
        "home.checkin.title": "रोज़ की हाज़िरी",
        "home.checkin.body": "आज के %d सिक्के लें",
        "home.checkin.body.plain": "आज के सिक्के लें",
        "home.checkin.claim": "लें",
        "home.checkin.toast": "+%d सिक्के · लगातार हाज़िरी",
        "home.search": "खोजें",
        "home.contentLanguage": "कहानियों की भाषा",
        "home.episodes": "%d एपिसोड",
        "home.firstFree": "पहले %d मुफ़्त",
        "home.playE1": "E1 चलाएँ",
        "home.featured": "%@, आज की ख़ास कहानी",
        "home.offline.title": "Katha से जुड़ नहीं पाए",
        "home.offline.body": "अपना कनेक्शन देखकर फिर कोशिश करें।",
        "home.offline.retry": "फिर कोशिश करें",
        "home.offline.retrying": "कोशिश हो रही है…",
        "home.loading": "कहानियाँ आ रही हैं",
        // ब्राउज़
        "browse.title": "ब्राउज़",
        "browse.all": "सभी",
        "browse.everything": "सब कुछ",
        "browse.empty.title": "यहाँ अभी कुछ नहीं",
        "browse.empty.body": "कोई और शैली चुनें — या भाषा बदलें।",
        // खोज
        "search.title": "खोज",
        "search.placeholder": "सीरीज़, कलाकार, कहानियाँ",
        "search.clear": "खोज मिटाएँ",
        "search.recent": "हाल की खोजें",
        "search.trending": "चर्चा में",
        "search.series": "सीरीज़",
        "search.people": "कलाकार",
        "search.eps": "%d एपिसोड",
        "search.empty.title": "“%@” के लिए कुछ नहीं मिला",
        "search.empty.body": "वर्तनी देख लें — या रोमांस, थ्रिलर जैसी शैली आज़माएँ।",
        "person.cast": "कलाकार",
        "person.series": "%d सीरीज़",
        // सीरीज़
        "series.pricing": "मुफ़्त · %1$d एपिसोड, उसके बाद हर एपिसोड %2$d सिक्के%3$@",
        "series.play1": "एपिसोड 1 चलाएँ",
        "series.continue": "E%d से आगे देखें",
        "series.save": "मेरी सूची में जोड़ें",
        "series.unsave": "मेरी सूची से हटाएँ",
        "series.reminderHint": "इस सीरीज़ के नए एपिसोड की सूचना",
        "series.episode": "एपिसोड %d",
        "series.episode.free": ", मुफ़्त",
        "series.episode.locked": ", लॉक",
        "series.episode.here": ", यहीं से जारी रखें",
        // मेरी सूची
        "mylist.empty.title": "अभी कुछ सहेजा नहीं",
        "mylist.empty.body": "किसी भी सीरीज़ पर बुकमार्क दबाएँ — वह यहाँ आ जाएगी।",
        "mylist.remove": "मेरी सूची से हटाएँ",
        // देखना जारी रखें
        "continue.left.minutes": "%d मिनट बाकी",
        "continue.left.under": "1 मिनट से कम बाकी",
        "continue.resume": "आगे देखें",
        "continue.resumeHint": "एपिसोड वहीं से चलता है",
        // वॉलेट
        "wallet.title": "वॉलेट",
        "wallet.balance": "बैलेंस",
        "wallet.getCoins": "सिक्के लें",
        "wallet.allPacks": "सभी पैक",
        "wallet.split": "%1$d खरीदे · %2$d बोनस — बोनस पहले खर्च होता है। सिक्के कभी खत्म नहीं होते।",
        "wallet.footer": "भुगतान Apple संभालता है। दामों में GST शामिल है। खाता रहते सिक्के कभी खत्म नहीं होते।",
        "wallet.history": "इतिहास",
        "wallet.history.empty": "अभी कोई लेन-देन नहीं — खरीदे और खर्च किए सिक्के यहाँ दिखेंगे।",
        "wallet.today": "आज",
        "wallet.yesterday": "कल",
        "wallet.row.purchase": "सिक्कों का पैक",
        "wallet.row.bonus": "बोनस सिक्के",
        "wallet.row.checkin": "रोज़ की हाज़िरी",
        "wallet.row.referral": "रेफ़रल इनाम",
        "wallet.row.bundle": "पूरी सीरीज़ अनलॉक",
        "wallet.row.unlock": "एपिसोड अनलॉक",
        "wallet.row.refund": "रिफ़ंड",
        "wallet.row.adjust": "सपोर्ट से सुधार",
        "wallet.src.web": "वेब स्टोर",
        "wallet.src.appstore": "App Store",
        // प्रोफ़ाइल
        "profile.title": "प्रोफ़ाइल",
        "profile.invoices": "इनवॉइस",
        "profile.replayTips": "टिप्स दोबारा देखें",
        "profile.signOut": "साइन आउट",
        "profile.signIn": "साइन इन",
        "profile.member": "Katha सदस्य",
        "profile.signedIn": "साइन इन हैं",
        "profile.guest.title": "आप मेहमान के तौर पर देख रहे हैं",
        "profile.guest.body": "सिक्के और अपनी जगह सहेजने के लिए खाता बनाएँ।",
        "profile.coins": "%d सिक्के",
        "profile.version": "वर्ज़न %@",
        // इनवॉइस
        "invoices.empty.title": "अभी कोई इनवॉइस नहीं",
        "invoices.empty.body": "Katha की वेबसाइट (UPI) से खरीदे सिक्कों की इनवॉइस यहाँ आती है। App Store की खरीद की इनवॉइस Apple देता है।",
        // मदद
        "help.common": "आम सवाल",
        "help.contact": "संपर्क",
        "help.contact.footer": "IT नियम 2021 के अनुसार शिकायत 24 घंटे में स्वीकार और 15 दिन में हल की जाती है। सहायता का समय सुबह 9 से रात 9 बजे (IST)।",
        "help.faq.coins.q": "सिक्के कैसे काम करते हैं?",
        "help.faq.coins.a": "हर सीरीज़ के पहले %1$d एपिसोड मुफ़्त हैं। उसके बाद हर एपिसोड %2$d सिक्के%3$@ का पड़ता है। पैक एक बार खरीदें — सिक्के कभी खत्म नहीं होते।",
        "help.faq.coins.a.plain": "हर सीरीज़ के पहले कुछ एपिसोड मुफ़्त हैं; उसके बाद हर एपिसोड सिक्कों से खुलता है। पैक एक बार खरीदें — सिक्के कभी खत्म नहीं होते।",
        "help.faq.missing.q": "पैसे कट गए पर सिक्के नहीं मिले",
        "help.faq.missing.a": "वॉलेट को नीचे खींचकर रिफ़्रेश करें, फिर “खरीदारी वापस लाएँ” दबाएँ। कुछ मिनट में भी सिक्के न आएँ तो सहायता से संपर्क करें — जाँची हुई असफल खरीद के सिक्के दोबारा जोड़े जाते हैं।",
        "help.faq.refunds.q": "रिफ़ंड और रद्द करना",
        "help.faq.refunds.a": "App Store से की गई खरीद का रिफ़ंड Apple अपनी नीति के तहत देता है (reportaproblem.apple.com)। वेब से खरीदे सिक्के, अगर खर्च न हुए हों, 7 दिन में वापस हो सकते हैं।",
        "help.faq.parental.q": "पैरेंटल कंट्रोल",
        "help.faq.parental.a": "सेटिंग्स → पैरेंटल लॉक में PIN लगाएँ। उसके बाद U/A 16+ और A रेटेड कहानियाँ चलाने से पहले PIN पूछा जाएगा।",
        "help.grievance.header": "शिकायत दर्ज करें",
        "help.grievance.footer": "सीधे शिकायत अधिकारी तक जाती है, ईमेल की ज़रूरत नहीं।",
        "help.grievance.contact": "आपका ईमेल या फ़ोन",
        "help.grievance.subject": "क्या दिक्कत हुई?",
        "help.grievance.file": "शिकायत भेजें",
        "help.grievance.filing": "भेजी जा रही है…",
        "help.grievance.ack": "%@ के तौर पर दर्ज। हम 24 घंटे में स्वीकार और 15 दिन में हल करेंगे।",
        "help.grievance.error": "अभी दर्ज नहीं हो पाई — नीचे दिए पते पर ईमेल कर दें।",
        // प्लेयर
        "player.like": "पसंद",
        "player.liked": "पसंद किया",
        "player.share": "शेयर",
        "player.timeLeft": "%@ बाकी",
        "player.locked": "एपिसोड %d लॉक है",
        "player.unlockFor": "%d सिक्कों में अनलॉक करें",
        "player.unlockForRupees": "%1$d सिक्कों में अनलॉक करें  ·  ≈ ₹%2$@",
        "player.offline.title": "कनेक्शन टूट गया",
        "player.offline.retry": "फिर कोशिश करें",
        "player.upNext": "आगे: E%d",
        "player.playNext": "अगला एपिसोड चलाएँ",
        "player.finished": "आपने %@ पूरी देख ली",
        "player.finished.body": "नई कहानियाँ हर हफ़्ते आती हैं।",
        "player.backHome": "होम पर लौटें",
        "player.recording.title": "रिकॉर्डिंग नहीं चलती",
        "player.recording.body": "स्क्रीन रिकॉर्डिंग बंद होते ही एपिसोड फिर चलने लगेगा।",
        "player.screenshot": "एपिसोड के स्क्रीनशॉट लेने की अनुमति नहीं है",
        "player.autoUnlocked": "−%1$d सिक्के · E%2$d अनलॉक",
        "player.rate2x": "दोगुनी रफ़्तार से चल रहा है",
        "player.subtitles.footer": "सबटाइटल आपके सिस्टम की कैप्शन शैली में दिखते हैं। जो भाषा इस स्ट्रीम में अभी नहीं है, वह याद रखी जाती है और उपलब्ध होते ही लग जाती है।",
        "player.track.remembered": "याद रखी गई",
        "player.track.notHere": "इस एपिसोड में नहीं",
        "drawer.title": "एपिसोड",
        "drawer.count": "%1$d · 1–%2$d मुफ़्त",
        "drawer.autoUnlock.caption": "एपिसोड शुरू होने पर ही %d सिक्के लगते हैं",
        "drawer.autoUnlock.caption.short": "सिक्के सिर्फ़ एपिसोड शुरू होने पर लगते हैं",
    ]
}
