import Foundation

// App-language strings (English / हिन्दी) for the chrome the viewer reads most:
// tab titles, Settings labels, the paywall's primary copy and the help
// assistant. A code table rather than .strings files: generate_xcodeproj.rb
// bundles only the asset catalog, the privacy manifest and the fonts, so a
// Localizable.strings would never reach the app bundle. Content languages
// (hi/ta/te) are a separate, multi-select choice — this is the UI language.
//
// Usage: `model.t("tab.home")` (AppModel reads its `uiLanguage`). Keys missing a
// Hindi line fall back to English so a half-translated key never renders empty.

enum L10n {
    static let supported: [(code: String, native: String, name: String)] = [
        ("en", "English", "English"),
        ("hi", "हिन्दी", "Hindi"),
    ]

    static func string(_ key: String, lang: String) -> String {
        if lang == "hi", let s = hi[key] { return s }
        return en[key] ?? key
    }

    private static let en: [String: String] = [
        // Tabs
        "tab.home": "Home",
        "tab.browse": "Browse",
        "tab.mylist": "My list",
        "tab.profile": "Profile",
        // Settings
        "settings.title": "Settings",
        "settings.language": "Language",
        "settings.contentLanguage": "Content language",
        "settings.appLanguage": "App language",
        "settings.appLanguage.footer": "The language of menus and buttons. Stories keep their own languages.",
        "settings.playback": "Playback",
        "settings.dataSaver": "Data saver",
        "settings.autoUnlock": "Auto-unlock next episodes",
        "settings.previews": "Autoplay trailers",
        "settings.previews.caption": "Muted previews on Home",
        "settings.playback.footer": "Data saver caps streaming quality on mobile data. Auto-unlock charges coins only when an episode starts.",
        "settings.notifications": "Notifications",
        "settings.alerts": "New episode alerts",
        "settings.alerts.footer": "One alert when your next episode drops. Never between 11 pm and 8 am, at most two a day.",
        "settings.parental": "Parental lock",
        "settings.parental.set": "Set parental lock",
        "settings.parental.change": "Change parental lock",
        "settings.parental.remove": "Remove parental lock",
        "settings.parental.footer": "A PIN is asked before playing U/A 16+ and A-rated titles (IT Rules 2021). Changing or removing the lock asks for the current PIN.",
        "settings.account": "Account",
        "settings.signOutDevices": "Sign out of other devices",
        "settings.signOutDevices.done": "Other devices were signed out",
        "settings.about": "About",
        "settings.help": "Help & grievance",
        "settings.legal": "Terms · Privacy Notice",
        "settings.delete": "Delete account",
        // Paywall + packs
        "paywall.unlock": "Unlock episode",
        "paywall.unlocking": "Unlocking…",
        "paywall.getCoins": "Get coins",
        "paywall.buyOnce": "Buy once, keep watching",
        "packs.title": "Coin packs",
        "packs.footer": "Payment is handled by Apple. Coins never expire while your account exists. Prices include GST.",
        "packs.restore": "Restore purchases",
        "packs.restored": "Purchases restored",
        "packs.terms": "Terms",
        "packs.confirming": "Confirming with the App Store. Your episode unlocks automatically.",
        "packs.stillConfirming": "Still confirming — you can keep browsing.",
        "packs.pending.banner": "This purchase needs approval from your family organizer. We'll unlock the episode the moment it's approved.",
        "packs.pending.notCharged": "You haven't been charged yet.",
        "packs.failed": "Payment didn't go through. You weren't charged.",
        "packs.retry": "Retry",
        "packs.done": "Done",
        "packs.credited": "coins added",
        // Continue watching
        "continue.title": "Continue watching",
        "continue.seeAll": "See all",
        "continue.empty.title": "Nothing in progress",
        "continue.empty.body": "Start any episode and it shows up here, right where you left it.",
        // Help assistant
        "assistant.title": "Chat with us",
        "assistant.card": "Answers in Hindi and English. A person steps in when needed.",
        "assistant.greeting": "Hi! Ask me about coins, free episodes, refunds, the parental lock, languages or playback — in English or Hindi.",
        "assistant.placeholder": "Ask a question",
        "assistant.person": "Talk to a person",
        "assistant.fallback": "I don't have an answer for that yet. Tap \"Talk to a person\" and the grievance officer picks it up — acknowledged within 24 hours.",
        "assistant.footer": "Answers come from Katha's built-in help — no AI service is contacted.",
        "assistant.send": "Send",
        // Reminders
        "reminder.on": "Reminder on",
        "reminder.off": "Remind me",
        "reminder.toast.on": "We'll nudge you when a new episode drops",
        "reminder.toast.off": "Reminder turned off",
        // Player
        "player.tracks": "Audio & subtitles",
        "player.audio": "Audio",
        "player.subtitles": "Subtitles",
        "player.subtitles.off": "Off",
        "player.subtitles.none": "No subtitles for this episode yet.",
        // Parental lock recovery
        "pin.forgot": "Forgot PIN?",
        "pin.reset.title": "Reset the parental lock",
        "pin.reset.body": "We'll send a code to the phone on this account. Entering it removes the lock; set a new PIN afterwards in Settings.",
        "pin.reset.send": "Send code",
        "pin.reset.enter": "Enter the code",
        "pin.reset.guest": "Resetting the PIN needs a phone sign-in. Sign in with your number from Profile, then come back here.",
        "pin.reset.done": "Parental lock removed",
    ]

    private static let hi: [String: String] = [
        "tab.home": "होम",
        "tab.browse": "ब्राउज़",
        "tab.mylist": "मेरी सूची",
        "tab.profile": "प्रोफ़ाइल",
        "settings.title": "सेटिंग्स",
        "settings.language": "भाषा",
        "settings.contentLanguage": "कहानियों की भाषा",
        "settings.appLanguage": "ऐप की भाषा",
        "settings.appLanguage.footer": "मेनू और बटनों की भाषा। कहानियाँ अपनी भाषा में ही रहती हैं।",
        "settings.playback": "प्लेबैक",
        "settings.dataSaver": "डेटा सेवर",
        "settings.autoUnlock": "अगले एपिसोड अपने आप अनलॉक करें",
        "settings.previews": "ट्रेलर अपने आप चलाएँ",
        "settings.previews.caption": "होम पर बिना आवाज़ के प्रीव्यू",
        "settings.playback.footer": "डेटा सेवर मोबाइल डेटा पर क्वालिटी सीमित रखता है। ऑटो-अनलॉक सिर्फ़ एपिसोड शुरू होने पर सिक्के लेता है।",
        "settings.notifications": "सूचनाएँ",
        "settings.alerts": "नए एपिसोड की सूचना",
        "settings.alerts.footer": "अगला एपिसोड आते ही एक सूचना। रात 11 से सुबह 8 के बीच कभी नहीं, दिन में ज़्यादा से ज़्यादा दो।",
        "settings.parental": "पैरेंटल लॉक",
        "settings.parental.set": "पैरेंटल लॉक लगाएँ",
        "settings.parental.change": "पैरेंटल लॉक बदलें",
        "settings.parental.remove": "पैरेंटल लॉक हटाएँ",
        "settings.parental.footer": "U/A 16+ और A रेटेड कहानियाँ चलाने से पहले PIN पूछा जाता है (IT नियम 2021)। लॉक बदलने या हटाने के लिए मौजूदा PIN चाहिए।",
        "settings.account": "खाता",
        "settings.signOutDevices": "बाकी डिवाइस से साइन आउट करें",
        "settings.signOutDevices.done": "बाकी डिवाइस साइन आउट हो गए",
        "settings.about": "जानकारी",
        "settings.help": "मदद और शिकायत",
        "settings.legal": "शर्तें · गोपनीयता सूचना",
        "settings.delete": "खाता हटाएँ",
        "paywall.unlock": "एपिसोड अनलॉक करें",
        "paywall.unlocking": "अनलॉक हो रहा है…",
        "paywall.getCoins": "सिक्के लें",
        "paywall.buyOnce": "एक बार खरीदें, देखते रहें",
        "packs.title": "सिक्कों के पैक",
        "packs.footer": "भुगतान Apple संभालता है। खाता रहते सिक्के कभी खत्म नहीं होते। दामों में GST शामिल है।",
        "packs.restore": "खरीदारी वापस लाएँ",
        "packs.restored": "खरीदारी वापस आ गई",
        "packs.terms": "शर्तें",
        "packs.confirming": "App Store से पुष्टि हो रही है। आपका एपिसोड अपने आप अनलॉक हो जाएगा।",
        "packs.stillConfirming": "पुष्टि अभी बाकी है — आप देखते रह सकते हैं।",
        "packs.pending.banner": "इस खरीद के लिए आपके फ़ैमिली ऑर्गनाइज़र की मंज़ूरी चाहिए। मंज़ूरी मिलते ही एपिसोड अनलॉक हो जाएगा।",
        "packs.pending.notCharged": "अभी आपसे कोई पैसा नहीं लिया गया है।",
        "packs.failed": "भुगतान नहीं हो पाया। आपसे पैसा नहीं लिया गया।",
        "packs.retry": "फिर कोशिश करें",
        "packs.done": "ठीक है",
        "packs.credited": "सिक्के जुड़ गए",
        "continue.title": "देखना जारी रखें",
        "continue.seeAll": "सभी देखें",
        "continue.empty.title": "अभी कुछ चल नहीं रहा",
        "continue.empty.body": "कोई भी एपिसोड शुरू करें — वह यहाँ वहीं से मिलेगा जहाँ आपने छोड़ा था।",
        "assistant.title": "हमसे बात करें",
        "assistant.card": "हिन्दी और अंग्रेज़ी में जवाब। ज़रूरत पड़ने पर एक इंसान जुड़ता है।",
        "assistant.greeting": "नमस्ते! सिक्के, मुफ़्त एपिसोड, रिफ़ंड, पैरेंटल लॉक, भाषा या प्लेबैक के बारे में पूछिए — हिन्दी या अंग्रेज़ी में।",
        "assistant.placeholder": "सवाल पूछें",
        "assistant.person": "किसी इंसान से बात करें",
        "assistant.fallback": "इसका जवाब अभी मेरे पास नहीं है। \"किसी इंसान से बात करें\" दबाएँ — शिकायत अधिकारी 24 घंटे में जवाब देते हैं।",
        "assistant.footer": "जवाब Katha की अपनी मदद-सूची से आते हैं — किसी AI सेवा से संपर्क नहीं होता।",
        "assistant.send": "भेजें",
        "reminder.on": "याद दिलाना चालू",
        "reminder.off": "याद दिलाएँ",
        "reminder.toast.on": "नया एपिसोड आते ही हम बताएँगे",
        "reminder.toast.off": "याद दिलाना बंद",
        "player.tracks": "ऑडियो और सबटाइटल",
        "player.audio": "ऑडियो",
        "player.subtitles": "सबटाइटल",
        "player.subtitles.off": "बंद",
        "player.subtitles.none": "इस एपिसोड के सबटाइटल अभी नहीं हैं।",
        "pin.forgot": "PIN भूल गए?",
        "pin.reset.title": "पैरेंटल लॉक रीसेट करें",
        "pin.reset.body": "इस खाते के फ़ोन पर कोड भेजा जाएगा। कोड डालते ही लॉक हट जाएगा; बाद में सेटिंग्स में नया PIN लगाएँ।",
        "pin.reset.send": "कोड भेजें",
        "pin.reset.enter": "कोड डालें",
        "pin.reset.guest": "PIN रीसेट के लिए फ़ोन से साइन इन ज़रूरी है। प्रोफ़ाइल से अपने नंबर से साइन इन करें, फिर यहाँ लौटें।",
        "pin.reset.done": "पैरेंटल लॉक हट गया",
    ]
}
