"""Dev media location — the local stand-in for CDN delivery (SAD §7.1).

Covers and placeholder HLS live in the repo's `media/` directory, generated by
tools/generate_placeholder_media.py + tools/generate_covers.py. Production swaps
this for CloudFront/Cloudflare signed URLs; nothing here is a real secret.
"""
from __future__ import annotations

import os
from pathlib import Path

REPO_MEDIA = Path(__file__).resolve().parents[4] / "media"


def media_dir() -> Path:
    return Path(os.environ.get("KATHA_MEDIA_DIR", str(REPO_MEDIA)))
