#!/usr/bin/env python3
"""Generate the admin-api contract artifacts (admin review #107).

Reads the FastAPI app's live OpenAPI schema and writes:
  contracts/openapi/admin-api.json          — the committed contract
  web/admin/src/api/paths.generated.ts      — every method+path the server owns

Two drift gates consume these so the client can never silently call a path the
server doesn't serve:
  backend  services/admin-api/tests/test_contract.py — committed JSON == live app
  frontend web/admin/test/contract.test.ts — every path client.ts calls exists

Run from the repo root after changing admin-api routes:
  backend/.venv/bin/python tools/gen_admin_types.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"
for p in ("packages/ledger", "packages/domain", "packages/infra",
          "services/admin-api", "services/core-api"):
    sys.path.insert(0, str(BACKEND / p))


def openapi() -> dict:
    from admin_app.main import app
    return app.openapi()


def write_contract(spec: dict) -> Path:
    out = ROOT / "contracts" / "openapi" / "admin-api.json"
    out.write_text(json.dumps(spec, indent=2, sort_keys=True) + "\n")
    return out


def write_paths_ts(spec: dict) -> Path:
    rows = []
    for path, methods in sorted(spec["paths"].items()):
        for method in sorted(methods):
            rows.append(f'  "{method.upper()} {path}",')
    body = (
        "// GENERATED by tools/gen_admin_types.py — do not edit (#107).\n"
        "// The complete method+path inventory of admin-api. The contract test\n"
        "// verifies every call in client.ts against this list, so a renamed or\n"
        "// removed endpoint fails CI instead of failing an operator.\n\n"
        "export const ADMIN_API_PATHS = [\n" + "\n".join(rows) + "\n] as const;\n\n"
        "export type AdminApiPath = (typeof ADMIN_API_PATHS)[number];\n"
    )
    out = ROOT / "web" / "admin" / "src" / "api" / "paths.generated.ts"
    out.write_text(body)
    return out


if __name__ == "__main__":
    spec = openapi()
    a = write_contract(spec)
    b = write_paths_ts(spec)
    print(f"{a.relative_to(ROOT)}  ({len(spec['paths'])} paths)")
    print(b.relative_to(ROOT))
