"""baseline — the full current schema

Squash baseline for an app that has run on create_all until now: it materializes
the entire declarative metadata (13 tables) on a fresh database, so
`alembic upgrade head` reproduces exactly what the app expects. Every schema
change AFTER this point gets its own autogenerated revision
(`alembic revision --autogenerate -m "..."`).

Revision ID: 0001_baseline
Revises:
Create Date: 2026-09-03
"""
import sys
from pathlib import Path

from alembic import op

# Reuse the app's metadata so the baseline can never drift from the models.
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "packages" / "infra"))
from katha_infra.models import Base  # noqa: E402

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
